#!/usr/bin/env bats

load test_helper/common-setup

setup() {
  setup_common
  export TOOLBOX_ROOT="${TEST_TEMP}/toolbox"
  mkdir -p "$TOOLBOX_ROOT"/{configs/devcontainer,bin,lib/claude-toolbox}

  cp "${CLI}" "$TOOLBOX_ROOT/bin/claude-toolbox"
  cp "${CLI%bin/claude-toolbox}lib/claude-toolbox/"*.sh "$TOOLBOX_ROOT/lib/claude-toolbox/"
  LOCAL_CLI="$TOOLBOX_ROOT/bin/claude-toolbox"

  # Create mock devcontainer templates
  for lang in python node rust; do
    cat > "$TOOLBOX_ROOT/configs/devcontainer/${lang}.jsonc" << EOF
// AUTO-GENERATED by generate.sh — edit src/ files instead
{
  "name": "\${projectName} (${lang})",
  "image": "mcr.microsoft.com/devcontainers/${lang}:latest"
}
EOF
  done

  # Copy addon definitions
  local real_addons="${CLI%bin/claude-toolbox}configs/devcontainer/src/addons"
  if [[ -d "$real_addons" ]]; then
    mkdir -p "$TOOLBOX_ROOT/configs/devcontainer/src/addons"
    cp "$real_addons"/*.json "$TOOLBOX_ROOT/configs/devcontainer/src/addons/"
  fi

  # Create mock generate.sh
  cat > "$TOOLBOX_ROOT/configs/devcontainer/generate.sh" << 'EOF'
#!/usr/bin/env bash
echo "GENERATE_CALLED"
echo "ARGS=$*"
EOF
  chmod +x "$TOOLBOX_ROOT/configs/devcontainer/generate.sh"

  # Create a project directory to test devcontainer init
  PROJECT_DIR="${TEST_TEMP}/myproject"
  mkdir -p "$PROJECT_DIR"
}

teardown() {
  teardown_common
}

@test "devcontainer --help shows usage" {
  run "$LOCAL_CLI" devcontainer --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"devcontainer"* ]]
}

@test "devcontainer with no subcommand shows usage" {
  run "$LOCAL_CLI" devcontainer
  [ "$status" -eq 0 ]
  [[ "$output" == *"init"* ]]
  [[ "$output" == *"check"* ]]
  [[ "$output" == *"generate"* ]]
}

@test "devcontainer generate delegates to generate.sh" {
  run "$LOCAL_CLI" devcontainer generate
  [ "$status" -eq 0 ]
  [[ "$output" == *"GENERATE_CALLED"* ]]
}

@test "devcontainer generate passes language args" {
  run "$LOCAL_CLI" devcontainer generate python rust
  [ "$status" -eq 0 ]
  [[ "$output" == *"python"* ]]
  [[ "$output" == *"rust"* ]]
}

@test "devcontainer init creates .devcontainer/ with --lang" {
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --lang python
  [ "$status" -eq 0 ]
  [ -f "$PROJECT_DIR/.devcontainer/devcontainer.json" ]
}

@test "devcontainer init replaces \${projectName}" {
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --lang python
  [ "$status" -eq 0 ]

  run cat "$PROJECT_DIR/.devcontainer/devcontainer.json"
  [[ "$output" == *"myproject"* ]]
  [[ "$output" != *'${projectName}'* ]]
}

@test "devcontainer init strips auto-generated header" {
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --lang python
  [ "$status" -eq 0 ]

  run cat "$PROJECT_DIR/.devcontainer/devcontainer.json"
  [[ "$output" != *"AUTO-GENERATED"* ]]
}

@test "devcontainer init fails if .devcontainer/ already exists" {
  mkdir -p "$PROJECT_DIR/.devcontainer"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --lang python
  [ "$status" -eq 1 ]
  [[ "$output" == *"already exists"* ]]
}

@test "devcontainer init auto-detects python from requirements.txt" {
  touch "$PROJECT_DIR/requirements.txt"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init
  [ "$status" -eq 0 ]
  [ -f "$PROJECT_DIR/.devcontainer/devcontainer.json" ]

  run cat "$PROJECT_DIR/.devcontainer/devcontainer.json"
  [[ "$output" == *"python"* ]]
}

@test "devcontainer init auto-detects node from package.json" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init
  [ "$status" -eq 0 ]

  run cat "$PROJECT_DIR/.devcontainer/devcontainer.json"
  [[ "$output" == *"node"* ]]
}

@test "devcontainer init auto-detects rust from Cargo.toml" {
  touch "$PROJECT_DIR/Cargo.toml"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init
  [ "$status" -eq 0 ]

  run cat "$PROJECT_DIR/.devcontainer/devcontainer.json"
  [[ "$output" == *"rust"* ]]
}

@test "devcontainer init fails when language can't be detected" {
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init
  [ "$status" -eq 1 ]
  [[ "$output" == *"detect"* ]]
}

@test "devcontainer check verifies claude directory" {
  mkdir -p "$HOME/.claude"
  mkdir -p "$HOME/.ssh"
  touch "$HOME/.claude.json"
  run "$LOCAL_CLI" devcontainer check
  [[ "$output" == *".claude/"* ]]
}

# --- Addon tests ---

@test "devcontainer init --list-addons lists available addons" {
  run "$LOCAL_CLI" devcontainer init --list-addons
  [ "$status" -eq 0 ]
  [[ "$output" == *"playwright-mcp"* ]]
  [[ "$output" == *"browser automation"* ]]
}

@test "devcontainer init --with playwright-mcp adds postCreateCommand" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --with playwright-mcp
  [ "$status" -eq 0 ]
  [ -f "$PROJECT_DIR/.devcontainer/devcontainer.json" ]

  local content
  content="$(cat "$PROJECT_DIR/.devcontainer/devcontainer.json")"
  [[ "$content" == *"playwright"* ]]
  [[ "$content" == *"npx -y playwright install --with-deps chrome"* ]]
}

@test "devcontainer init --with playwright-mcp creates .mcp.json" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --with playwright-mcp
  [ "$status" -eq 0 ]
  [ -f "$PROJECT_DIR/.mcp.json" ]

  local content
  content="$(cat "$PROJECT_DIR/.mcp.json")"
  [[ "$content" == *"playwright"* ]]
  [[ "$content" == *"@playwright/mcp@latest"* ]]
  [[ "$content" == *"--no-sandbox"* ]]
}

@test "devcontainer init --with nonexistent fails with error" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --with nonexistent
  [ "$status" -eq 1 ]
  [[ "$output" == *"nonexistent"* ]]
}

@test "devcontainer init --with playwright-mcp --lang node works with explicit language" {
  cd "$PROJECT_DIR"
  run "$LOCAL_CLI" devcontainer init --lang node --with playwright-mcp
  [ "$status" -eq 0 ]
  [ -f "$PROJECT_DIR/.devcontainer/devcontainer.json" ]
  [ -f "$PROJECT_DIR/.mcp.json" ]

  local content
  content="$(cat "$PROJECT_DIR/.devcontainer/devcontainer.json")"
  [[ "$content" == *"node"* ]]
  [[ "$content" == *"playwright"* ]]
}

@test "devcontainer init --with playwright-mcp merges into existing .mcp.json" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"

  # Pre-existing .mcp.json with another server
  cat > "$PROJECT_DIR/.mcp.json" << 'EOF'
{
  "mcpServers": {
    "existing-server": {
      "type": "stdio",
      "command": "echo",
      "args": ["hello"]
    }
  }
}
EOF

  run "$LOCAL_CLI" devcontainer init --with playwright-mcp
  [ "$status" -eq 0 ]

  local content
  content="$(cat "$PROJECT_DIR/.mcp.json")"
  # Both the existing and new server should be present
  [[ "$content" == *"existing-server"* ]]
  [[ "$content" == *"playwright"* ]]
}

@test "devcontainer init with multiple --with flags applies all addons" {
  echo '{}' > "$PROJECT_DIR/package.json"
  cd "$PROJECT_DIR"

  # Create a second test addon
  cat > "$TOOLBOX_ROOT/configs/devcontainer/src/addons/test-addon.json" << 'EOF'
{
  "name": "test-addon",
  "description": "A test addon",
  "postCreateCommand": {
    "test-setup": "echo hello"
  },
  "mcpServers": {
    "test-server": {
      "type": "stdio",
      "command": "echo",
      "args": ["test"]
    }
  }
}
EOF

  run "$LOCAL_CLI" devcontainer init --with playwright-mcp --with test-addon
  [ "$status" -eq 0 ]

  local dc_content mcp_content
  dc_content="$(cat "$PROJECT_DIR/.devcontainer/devcontainer.json")"
  mcp_content="$(cat "$PROJECT_DIR/.mcp.json")"

  # Both addons' postCreateCommand entries
  [[ "$dc_content" == *"playwright"* ]]
  [[ "$dc_content" == *"test-setup"* ]]

  # Both addons' MCP servers
  [[ "$mcp_content" == *"playwright"* ]]
  [[ "$mcp_content" == *"test-server"* ]]
}
